# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

env:
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g @angular/cli@latest
    - run: npm install
    - run: node setTestData.js && echo $TEST_USER_PASSWORD
    - run: ng serve & sleep 30 && npm run cypress:run

  label:
    runs-on: ubuntu-latest
    steps:

    - name: major
      if: contains(github.head_ref, 'major_')
      uses: andymckay/labeler@master
      with:
        add-labels: "major"

    - name: minor
      if: contains(github.head_ref, 'minor_')
      uses: andymckay/labeler@master
      with:
        add-labels: "minor"

    - name: patch
      if: contains(github.head_ref, 'patch_')
      uses: andymckay/labeler@master
      with:
        add-labels: "patch"
