# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Master branch bump up version

on:
  push:
    branches:
      - master

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: echo "----"
      - run: echo "$GITHUB_CONTEXT"
      - run: git config --global user.name 'Git Schab'
      - run: git config --global user.email 'git@schab.it'

      - name: minor
        if: contains(toJSON(github.event.commits), 'minor_')
        run: npm version minor -m "[RELEASE] %s" --force
      
      - run: contains(toJSON(github.event.commits), 'minor_'))

      - run: echo ${{ github.event.label.name }}
      - run: git push
